// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var numbers = [0,2]; 
    var num1 = 1
	var num2 = 1;
	var holder = 0;
    //System.out.print(num1 + " " + num2 + " ");

    for (var i = 0; i < 10000; i++) {
        holder = num1;
        num1 = num2;
        num2 = holder + num2;
		
		var fibNumbers = (num1 + num2)
		if (fibNumbers % 2 ===0) {
			numbers.push(fibNumbers);
	
		}
		//console.log(fibNumbers)
		if (fibNumbers >= 4000000) {
			break;
			}
		
    }

function total (array) {

	var sum = array.reduce(function(prev, cur) {
		return prev + cur;
		
		});
	return sum;
};

console.log(numbers)
console.log(total(numbers))
// console.log(eval(numbers.join("+")));